name = "fetch-airtable-data"
account_id = "eec00739050a8a4cbf359a1dedb8cad3"
workers_dev = true

kv_namespaces = [
  { binding = "LINKS_CACHE", id = "02ae18d056774dd8b0619180c767a3e6" }
]

main = "worker/worker.js"  # Entry point for Worker.
compatibility_date = "2025-01-04"

[env.staging]
workers_dev = true
  
[env.production]
route = "fetch-airtable-data.jmajerus.workers.dev/*"
zone_id = "760804baffbf3cdb28094cab02683ea4"
kv_namespaces = [
  { binding = "LINKS_CACHE", id = "02ae18d056774dd8b0619180c767a3e6" }
]