name = "fetch-airtable-data"
account_id = "eec00739050a8a4cbf359a1dedb8cad3"
workers_dev = true

kv_namespaces = [
  { binding = "LINKS_CACHE", id = "link-cache" }
]

main = "worker.js"  # Specify the entry point here
compatibility_date = "2025-01-04"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[env.staging]
workers_dev = true

[env.production]
route = "api.majerus.us/*"
zone_id = "760804baffbf3cdb28094cab02683ea4"
