name: Deploy Worker to Cloudflare

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          script: fetch-airtable-data.js
          kv-namespaces: |
            - binding: LINKS_CACHE
              id: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
